[build]
command = "vue-cli-service build"
publish = "dist"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
CI = 1

[[plugins]]
package = "netlify-plugin-cypress"
